apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-secret
  namespace: monitoring
data:
  # Test data in base64 encoded format
  smtp_password: dGVzdC1wYXNzd29yZA==
  smtp_user: dGVzdC11c2VybmFtZQ==
